### ISSUE TITLE
Object expected error in IE11

### ISSUE THREAD

**Issue by jpike88** [es-shims/Number.isNaN#2]
![screen shot 2018-10-09 at 9 41 07 am](https://user-images.githubusercontent.com/9585787/46643702-76ecaf80-cba7-11e8-91c2-21feb34efbdf.png)

**Comment by leonderijke** [comment]
I can't reproduce this. Here's a CodePen I tested in IE11 that works fine.

Can you provide a reduced test case that I can look into?

**Comment by jpike88** [comment]
Sorry, I moved onto the ```is-nan``` library and it works ok. I was moving fast so there's even a chance this was a false positive
